spring:
  graphql:
    graphiql:
      enabled: true
    schema:
      introspection:
        enabled: true
      printer:
        enabled: true

vetka:
  gateway:
    path: "/"
    persistence:
      engine: mongo
      mongo:
        database-name: "vetka_gateway"