spring:
  graphql:
    graphiql:
      enabled: true
    schema:
      introspection:
        enabled: true
      printer:
        enabled: true

vetka:
  gateway:
    endpoint:
      path: "/"
    transport:
      engine: httpclient
      httpclient:
        http-version: "1.1"
        connect-timeout: 30
        read-timeout: 600
    persistence:
      engine: mongo
      mongo:
        database-name: "vetka_gateway"

logging:
  level:
    root: DEBUG